import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Mobile Sales Project\Mobile_datasets.csv")

print(df.head())

# 1. Total Revenue Generated by Each Brand

df['Revenue'] = df['Units Sold'] * df['Price']

brand_revenue = df.groupby('Brand')['Revenue'].sum().sort_values(ascending=False)

print("\nBrand Revenue:")
print(brand_revenue)

brand_revenue.plot(kind='bar', figsize=(10,5))
plt.title("Total Revenue by Brand")
plt.xlabel("Brand")
plt.ylabel("Revenue")
plt.show()

# 2. Top 5 Selling Mobile Models

top_models = df.groupby('Model')['Units Sold'].sum().sort_values(ascending=False).head(5)

print("\nTop Selling Models:")
print(top_models)

top_models.plot(kind='bar', figsize=(10,5))
plt.title("Top 5 Selling Mobile Models")
plt.xlabel("Model")
plt.ylabel("Units Sold")
plt.show()

# 3. Average Rating by Brand

brand_rating = df.groupby('Brand')['Rating'].mean().sort_values(ascending=False)

print("\nAverage Rating by Brand:")
print(brand_rating)

brand_rating.plot(kind='bar', figsize=(10,5))
plt.title("Average Rating by Brand")
plt.xlabel("Brand")
plt.ylabel("Average Rating")
plt.show()

# 4. City-wise Revenue Analysis

city_revenue = df.groupby('City')['Revenue'].sum().sort_values(ascending=False)

print("\nCity Revenue:")
print(city_revenue)

city_revenue.plot(kind='bar', figsize=(12,5))
plt.title("City-wise Revenue")
plt.xlabel("City")
plt.ylabel("Revenue")
plt.show()

# 5. Payment Method Usage

payment_method = df['Method'].value_counts()

print("\nPayment Methods:")
print(payment_method)

payment_method.plot(kind='pie', autopct='%1.1f%%', figsize=(7,7))
plt.title("Payment Method Usage")
plt.ylabel("")
plt.show()

# 6. Top Customers by Spending

top_customers = df.groupby('Customer')['Revenue'].sum().sort_values(ascending=False).head(10)

print("\nTop Customers:")
print(top_customers)

top_customers.plot(kind='bar', figsize=(12,5))
plt.title("Top 10 Customers by Spending")
plt.xlabel("Customer")
plt.ylabel("Total Spending")
plt.show()

# 7. Day-wise Sales Analysis

day_sales = df.groupby('Day')['Revenue'].sum().sort_values(ascending=False)

print("\nDay-wise Revenue:")
print(day_sales)

day_sales.plot(kind='bar', figsize=(10,5))
plt.title("Revenue by Day")
plt.xlabel("Day")
plt.ylabel("Revenue")
plt.show()

# 8. Average Customer Age by Brand

brand_age = df.groupby('Brand')['Age'].mean().sort_values()

print("\nAverage Customer Age:")
print(brand_age)

brand_age.plot(kind='bar', figsize=(10,5))
plt.title("Average Customer Age by Brand")
plt.xlabel("Brand")
plt.ylabel("Average Age")
plt.show()

# 9. Monthly Revenue Trend

df['Revenue'] = df['Units Sold'] * df['Price']
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Month'] = df['Date'].dt.month

monthly_revenue = df.groupby('Month')['Revenue'].sum()
print("\nMonthly Revenue:")
print(monthly_revenue)

monthly_revenue.plot(kind='line', marker='o', figsize=(10,5))

plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.show()

# 10. Top Rated Mobile Models

top_rated_models = df.groupby('Model')['Rating'].mean().sort_values(ascending=False).head(10)

print("\nTop Rated Models:")
print(top_rated_models)

top_rated_models.plot(kind='bar', figsize=(12,5))
plt.title("Top Rated Mobile Models")
plt.xlabel("Model")
plt.ylabel("Average Rating")
plt.show()

# 11. Brand-wise Units Sold

brand_units = df.groupby('Brand')['Units Sold'].sum().sort_values(ascending=False)

print("\nBrand-wise Units Sold:")
print(brand_units)

brand_units.plot(kind='bar', figsize=(10,5))
plt.title("Brand-wise Units Sold")
plt.xlabel("Brand")
plt.ylabel("Units Sold")
plt.show()

# 12. Most Expensive Phones Purchased

expensive_phones = df[['Customer', 'Model', 'Price']].sort_values(by='Price', ascending=False).head(10)

print("\nMost Expensive Phones:")
print(expensive_phones)
