CREATE DATABASE mobile_sales;

Use mobile_sales;

SELECT * FROM mobile_datasets;

-- 1. Total Revenue Generated by Each Brand
SELECT `Brand`, SUM(`Units Sold` * `Price`) AS Total_Revenue
FROM mobile_datasets
GROUP BY `Brand`
ORDER BY Total_Revenue DESC;

-- 2. Top 5 Selling Mobile Models
SELECT `Model`, SUM(`Units Sold`) AS Total_Units_Sold
FROM mobile_datasets
GROUP BY `Model`
ORDER BY Total_Units_Sold DESC
LIMIT 5;

-- 3. Average Rating Given to Each Brand
SELECT `Brand`, AVG(`Rating`) AS Average_Rating
FROM mobile_datasets
GROUP BY `Brand`
ORDER BY Average_Rating DESC;

-- 4. City-wise Revenue Analysis
SELECT `City`, SUM(`Units Sold` * `Price`) AS City_Revenue
FROM mobile_datasets
GROUP BY `City`
ORDER BY City_Revenue DESC;

-- 5. Payment Method Usage Count
SELECT `Method`,COUNT(*) AS Total_Transactions
FROM mobile_datasets
GROUP BY `Method`
ORDER BY Total_Transactions DESC;

-- 6. Day-wise Sales Performance
SELECT `Day`, SUM(`Units Sold`) AS Total_Units_Sold , SUM(`Units Sold` * `Price`) AS Total_Revenue
FROM mobile_datasets
GROUP BY `Day`
ORDER BY Total_Revenue DESC;

-- 7. Monthly Revenue Trend
SELECT MONTH(STR_TO_DATE(`Date`, '%d-%m-%Y')) AS Month_Number , SUM(`Units Sold` * `Price`) AS Monthly_Revenue
FROM mobile_datasets
GROUP BY Month_Number
ORDER BY Month_Number;

-- 8. Top Rated Mobile Models
SELECT `Model`, AVG(`Rating`) AS Average_Rating
FROM mobile_datasets
GROUP BY `Model`
ORDER BY Average_Rating DESC;

-- 9. Brand-wise Total Units Sold
SELECT `Brand`, SUM(`Units Sold`) AS Total_Units
FROM mobile_datasets
GROUP BY `Brand`
ORDER BY Total_Units DESC;

-- 10. Customers Who Purchased Most Expensive Phones
SELECT `Customer`,`Model`,`Price`
FROM mobile_datasets
ORDER BY `Price` DESC
LIMIT 10;